[versions]
dependency = "1.1.3"
font = "6.4.2"
h2db = "2.2.224"
klogging = "3.0.5"
kotlinversion = "1.9.10"
manes = "0.48.0"
node = "7.0.0"
owasp = "8.4.0"
snakeyaml = "2.2"
sonarqube = "4.3.1.3277"
springboot = "3.1.4"
thymeleaf = "3.3.0"
swagger = "2.2.0"