[versions]
dependency = "1.1.3"
font = "6.4.2"
h2db = "2.2.220"
klogging = "3.0.5"
kotlinversion = "1.9.10"
manes = "0.47.0"
node = "7.0.0"
owasp = "8.4.0"
snakeyaml = "2.1"
sonarqube = "4.3.0.3225"
springboot = "3.1.3"
thymeleaf = "3.2.1"
swagger = "2.2.0"