[versions]
dependency = "1.1.4"
font = "6.4.2"
h2db = "2.2.224"
klogging = "3.0.5"
kotlinversion = "1.9.21"
manes = "0.50.0"
node = "7.0.1"
owasp = "9.0.4"
snakeyaml = "2.2"
sonarqube = "4.4.1.3373"
springboot = "3.2.0"
thymeleaf = "3.3.0"
swagger = "2.3.0"