[versions]
dependency = "1.1.6"
font = "6.5.2"
h2db = "2.3.232"
klogging = "7.0.0"
kotlinversion = "2.0.20"
manes = "0.51.0"
node = "7.0.2"
owasp = "10.0.4"
snakeyaml = "2.3"
sonarqube = "5.1.0.4882"
springboot = "3.3.4"
thymeleaf = "3.3.0"
swagger = "2.6.0"