[versions]
dependency = "1.1.0"
flyway = "9.17.0"
font = "6.4.0"
h2db = "2.1.214"
klogging = "3.0.5"
kotlinversion = "1.8.21"
manes = "0.46.0"
node = "5.0.0"
owasp = "8.2.1"
snakeyaml = "2.0"
sonarqube = "4.2.0.3129"
springboot = "3.1.0"
thymeleaf = "3.2.1"
swagger = "2.1.0"