[versions]
dependency = "1.1.4"
font = "6.5.2"
h2db = "2.2.224"
klogging = "6.0.9"
kotlinversion = "1.9.23"
manes = "0.51.0"
node = "7.0.2"
owasp = "9.1.0"
snakeyaml = "2.2"
sonarqube = "5.0.0.4638"
springboot = "3.2.4"
thymeleaf = "3.3.0"
swagger = "2.5.0"