[versions]
dependency = "1.1.4"
font = "6.5.1"
h2db = "2.2.224"
klogging = "6.0.3"
kotlinversion = "1.9.22"
manes = "0.51.0"
node = "7.0.2"
owasp = "9.0.9"
snakeyaml = "2.2"
sonarqube = "4.4.1.3373"
springboot = "3.2.3"
thymeleaf = "3.3.0"
swagger = "2.3.0"