[versions]
dependency = "1.1.0"
font = "6.4.0"
h2db = "2.2.220"
klogging = "3.0.5"
kotlinversion = "1.9.0"
manes = "0.47.0"
node = "5.0.0"
owasp = "8.3.1"
snakeyaml = "2.0"
sonarqube = "4.2.1.3168"
springboot = "3.1.1"
thymeleaf = "3.2.1"
swagger = "2.1.0"